apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fintech-dashboard
  description: Fintech dashboard demo application
  tags:
    - react
    - fintech
  annotations:
    github.com/project-slug: karimshaik-cmd/fintech
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
